version: '3.1'

services:
  mongo:
    container_name: mongodb
    image: mongo:4.4.5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - 27017:27017
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: always

  node:
    container_name: node
    image: "node:14.16-alpine3.10"
    working_dir: /home/node/app
    depends_on:
      - mongo
    environment:
      - USERNAME=root
      - PASSWORD=example
      - PORT=3000
    volumes:
      - ./:/home/node/app
    ports:
      - 3000:3000
    restart: always
    command: "npm run start-dev"
